---
title: "Lab 06 - Ugly charts and Simpson's paradox"
author: "Ryan Wheat"
date: "02/23/23"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox)
library(mosaicData) 
```

```{r load-data}
staff <- read_csv("data/instructional-staff.csv")
```


### Exercise 1

```{r wide-to-long}

staff_long <- staff %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))

#plot long dataframe

staff_long %>%
  ggplot(aes(x = year,
             y = value,
             group = faculty_type,
             color = faculty_type)) +
  geom_line() +
  labs(title = "Instructional Staff Employment Plans", x = "Year", y = "Percentage of Hires", color = "Faculty Type")

```


### Exercise 2

This graph works, but given the question that we need to answer, I would collapse the full-time faculty into one category so that there is less clutter -- and the visual can be assessed in terms of full time faculty vs. part time faculty.


### Exercise 3

```{r fisheries-visual}

fisheries <- read_csv("data/fisheries.csv")



```

...

Add exercise headings as needed.
